# configuration
# fill in the course details
 
courseName: Computational Forensics and AI

# small title that is at the top of every page
subtitle: 11488/11688/11788 â€” Spring 2020

# baseurl is the same as the name of the repository
baseurl: /gh-syllabus

# url where the required reading is available to download
docsUrl: "" 

# url where the student's grading info is kept
gradingUrl: "" 


# change only if you know what you are doing
collections:
  syllabus:
    output: true
defaults:
  - scope:
      path: ""
      type: syllabus
    values:
      layout: unit
